### ISSUE TITLE
Deploy to Celo and Alfajores

### ISSUE THREAD

**Issue by michaelclark2** [ToucanProtocol/OffsetHelper#19]
now that the TCO2 retirements are working for Celo and Alfajores, is it possible to deploy OffsetHelper to Celo and Alfajores?

**Comment by itxtoledo** [comment]
According to the sdk they already have a contract on the alfajores network, but in my tests it doesn't work and analyzing the blockchain it seems to me that it never worked since there is no transaction for the presented address.

Contracts: https://github.com/ToucanProtocol/toucan-sdk/blob/main/src/utils/addresses.ts

On explorer:  https://alfajores.celoscan.io/address/0xacf9fd890f06e6f200339193a64c0952a164cb9d
![image](https://github.com/ToucanProtocol/OffsetHelper/assets/21026675/9975e991-8270-4328-9ef5-1ba3053658be)

**Comment by aspiers** [comment]
@itxtoledo Please can you give precise details of what doesn't work? Otherwise it's very hard to know what needs fixing ;-) Thanks!

@GigaHierz Checking you saw this!

**Comment by itxtoledo** [comment]
> @itxtoledo Please can you give precise details of what doesn't work? Otherwise it's very hard to know what needs fixing ;-) Thanks!
> 
> @GigaHierz Checking you saw this!

Of course, I'm creating a tutorial for the celo blockchain and I created this contract, you can interact with it directly through the celoscan website, but it doesn't work, it always gives an error when calculating the gas https://alfajores.celoscan.io/address/0xad55f12ee2f433aa47b2515486cfbd4f1c8afdf2 #code

**Comment by aspiers** [comment]
@itxtoledo Thanks for the info. However we really need the exact error pasted in here otherwise it's impossible to debug the issue.  I predict that the real error is not related to gas but let's see :-)

**Comment by GigaHierz** [comment]
@itxtoledo I am working on deploying the OffsetHelper on Celo, should be ready in the next weeks. I will inform you once it's done. The deployed contract you can find in the SDK is not yet working as there are no pools on Alfajores we can use to swap yet and the creation of these pools was blocked. I am working on a solution for that and will let you know once it was deployed on Alfajores & Celo.

**Comment by itxtoledo** [comment]
> @itxtoledo I am working on deploying the OffsetHelper on Celo, should be ready in the next weeks. I will inform you once it's done. The deployed contract you can find in the SDK is not yet working as there are no pools on Alfajores we can use to swap yet and the creation of these pools was blocked. I am working on a solution for that and will let you know once it was deployed on Alfajores & Celo.

How do I use it on the celo? You even sponsored a hackathon, I thought the pools would already be working.

**Comment by GigaHierz** [comment]
> > @itxtoledo I am working on deploying the OffsetHelper on Celo, should be ready in the next weeks. I will inform you once it's done. The deployed contract you can find in the SDK is not yet working as there are no pools on Alfajores we can use to swap yet and the creation of these pools was blocked. I am working on a solution for that and will let you know once it was deployed on Alfajores & Celo.
> 
> How do I use it on the celo? You even sponsored a hackathon, I thought the pools would already be working.

Hi @itxtoledo, 

You can use it once it's deployed. If you can't wait that long, I would suggest that you check the OffsetHelper contract that already exists and copy the necessary functionalities in your contract. 

Not sure what you mean with that the pools would be working. Yes, we deployed the contracts for the pool tokens like NCT on Celo and there are pools on Ubeswap created where you can exchange these tokens for e.g., cUSD. Just so far not yet on Alfajores as I mentioned above.

**Comment by GigaHierz** [comment]
Has been resolved by #20

**Comment by GigaHierz** [comment]
Has been resolved by #20
